### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by daemyung**

### CODE REVIEW

**Comment by daemyung** [comment]
Check it at https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/.

**Comment by daemyung** [comment]
Thanks for your library and I use it at https://github.com/daemyung/DirectX12. Do you mind I'm using this library and declaring at README.md?

**Comment by daemyung** [comment]
I read MSDN that is "However, when you read a .dds file, you should not rely on the DDSD_CAPS, DDSD_PIXELFORMAT, and DDSD_MIPMAPCOUNT flags being set because some writers of such a file might not set these flags." You can check it at https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header.

**Comment by septag** [comment]
First of all, thanks for your comments and using this in your repo, honestly, this lib is not battle tested yet, so any integrations and tests (especially with ktx files) are appreciated.

About the fix on ktx Id, the code is actually correct. If you look at `ddsktx_parse` function, I already read the first 4 bytes to detect between KTX/DDS data, the rest 8 bytes of Id is checked later.

The second fix is legit, so If you could remove your first fix, I would be happy to merge this PR

Thanks a bunch

**Comment by daemyung** [comment]
Yes... you are right. KTX ID is correct. Parse header correctly but checking KTX ID is wrong. It's memcpy so if both are identical then will return 0. So we need to pass when return value of memcpy is zero.

**Comment by daemyung** [comment]
If you want to check it on your machine, you can download ktx file at https://github.com/daemyung/DirectX12/blob/master/texture/asset/metalplate01_rgba.ktx.

**Comment by septag** [comment]
Ouch! yes, thank you

**Comment by septag** [comment]
btw, check out the new commit. 
I updated the repo today and it has an application for loading/viewing ktx/dds files, hope it helps to find more bugs. Currently, it has a problem with loading non-power-of-2 texture sizes. which I have to open an issue for it

**Pull request merged**
